server:
  PORT: "8080"
secret:
  ACCESS_KEY: 9851cd6b425d8720ef8e92879f16c95cb788c006
  RESET_KEY: dbae137398b2aa67b384e67a638f482110cc6257
mysql:
  DATABASE: "hospital"
  USERNAME: "root"
  PASSWORD: ""
  HOST: "localhost"
mongo:
  STRING: "mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb"
  DATABASE: "hospital"
jwt:
  ACCESS_TIME: 24 # in hour
  REFRESH_TIME: 240
  FORGOT_PASSWORD_TIME: 5 # in minutes
