// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	models "go-hospital-server/internal/core/entity/models"

	mock "github.com/stretchr/testify/mock"

	response "go-hospital-server/internal/core/entity/response"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: _a0
func (_m *AuthRepository) ChangePassword(_a0 models.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCode provides a mock function with given fields: _a0
func (_m *AuthRepository) FindByCode(_a0 string) (response.User, error) {
	ret := _m.Called(_a0)

	var r0 response.User
	if rf, ok := ret.Get(0).(func(string) response.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: _a0
func (_m *AuthRepository) FindByEmail(_a0 string) (response.User, error) {
	ret := _m.Called(_a0)

	var r0 response.User
	if rf, ok := ret.Get(0).(func(string) response.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0
func (_m *AuthRepository) Register(_a0 models.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeToken provides a mock function with given fields: _a0
func (_m *AuthRepository) RevokeToken(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveToken provides a mock function with given fields: _a0
func (_m *AuthRepository) SaveToken(_a0 models.Token) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Token) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateToken provides a mock function with given fields: _a0, _a1
func (_m *AuthRepository) UpdateToken(_a0 models.Token, _a1 models.Token) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Token, models.Token) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
