// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	models "go-hospital-server/internal/core/entity/models"

	mock "github.com/stretchr/testify/mock"

	response "go-hospital-server/internal/core/entity/response"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *UserRepository) Create(_a0 models.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *UserRepository) Delete(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *UserRepository) FindAll() ([]response.User, error) {
	ret := _m.Called()

	var r0 []response.User
	if rf, ok := ret.Get(0).(func() []response.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: _a0
func (_m *UserRepository) FindByID(_a0 int) (response.User, error) {
	ret := _m.Called(_a0)

	var r0 response.User
	if rf, ok := ret.Get(0).(func(int) response.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(response.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRFS provides a mock function with given fields: _a0, _a1, _a2
func (_m *UserRepository) FindByRFS(_a0 int, _a1 int, _a2 int) ([]response.User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []response.User
	if rf, ok := ret.Get(0).(func(int, int, int) []response.User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *UserRepository) Update(_a0 models.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
