basePath: /api
definitions:
  models.MedicRecord:
    properties:
      bloodTension:
        description: SerialNumber uint
        type: integer
      bodyTemperature:
        type: integer
      complaint:
        type: string
      diagnose:
        type: string
      height:
        type: integer
      id:
        type: integer
      medicalStaff:
        $ref: '#/definitions/models.MedicalStaff'
      medicalStaffID:
        type: integer
      patient:
        $ref: '#/definitions/models.Patient'
      patientID:
        type: integer
      prescription:
        type: string
      weight:
        type: integer
    type: object
  models.MedicalFacility:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.MedicalStaff:
    properties:
      facility:
        $ref: '#/definitions/models.MedicalFacility'
      facility_id:
        type: integer
      full_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.Patient:
    properties:
      address:
        type: string
      birthdate:
        type: string
      blood_type:
        type: string
      code:
        type: string
      full_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      medic_record:
        items:
          $ref: '#/definitions/models.MedicRecord'
        type: array
      resident_registration:
        type: string
    type: object
  models.Role:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.Token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      role_id:
        type: integer
      roles:
        $ref: '#/definitions/models.Role'
      status:
        type: integer
      updatedAt:
        type: string
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  response.Error:
    properties:
      error: {}
      message:
        type: string
    type: object
  response.MessageData:
    properties:
      data: {}
      message:
        type: string
    type: object
  response.MessageOnly:
    properties:
      message:
        type: string
    type: object
  response.User:
    properties:
      email:
        type: string
      facility:
        type: string
      full_name:
        type: string
      gender:
        type: string
      id:
        type: integer
      roles:
        type: string
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: server API for Holy Hospital Application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Holy Hospital Sever API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login and get Authorization Token
      parameters:
      - description: send request email, password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.User'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Login
      tags:
      - Authorization
  /logout:
    post:
      consumes:
      - application/json
      description: Route Path for Get New Access Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Token'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: Refresh Token
      tags:
      - Authorization
  /patient:
    get:
      consumes:
      - application/json
      description: Fetch All Patient Data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.MessageData'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/models.Patient'
                  type: array
              type: object
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: GetAllPatient
      tags:
      - Patient
    post:
      consumes:
      - application/json
      description: Fetch All Patient Data
      parameters:
      - description: patient details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Patient'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MessageOnly'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: CreatePatient
      tags:
      - Patient
  /patient/:id:
    get:
      consumes:
      - application/json
      description: Fetch Patient Data By ID
      parameters:
      - description: patient id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.MessageData'
            - properties:
                Data:
                  $ref: '#/definitions/models.Patient'
              type: object
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: GetPatientByID
      tags:
      - Patient
  /patient/:id/delete:
    delete:
      consumes:
      - application/json
      description: Fetch All Patient Data
      parameters:
      - description: patient id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MessageOnly'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: DeletePatient
      tags:
      - Patient
  /patient/:id/update:
    put:
      consumes:
      - application/json
      description: Fetch All Patient Data
      parameters:
      - description: patient id
        in: path
        name: id
        required: true
        type: integer
      - description: patient details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Patient'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MessageOnly'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: UpdatePatient
      tags:
      - Patient
  /refresh_token:
    post:
      consumes:
      - application/json
      description: Route Path for Get New Access Token
      parameters:
      - description: pass access token here
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Token'
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKey: []
      summary: Refresh Token
      tags:
      - Authorization
schemes:
- http
securityDefinitions:
  ApiKey:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
