name: Docker Push

on:
  pull_request:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: checkout repo
        uses: actions/checkout@v2.3.4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set Configuration
        run: "echo -e \"${{ secrets.CONFIG }}\" > config/config.yaml; ls config "
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: syarif74/go-hospital-server:latest
