name: Code Integration

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "go-hospital-server" #Must be unique in Heroku
          heroku_email: "ubed56pb@gmail.com"
          usedocker: true
          stack: "container"
